### ISSUE TITLE
Request for enableGunLights and adding NVGs Integration

### ISSUE THREAD

**Issue by Winter259** [kami-/admiral#24]
https://community.bistudio.com/wiki/enableGunLights on a group as it is spawned, changeable via a variable in settings.sqf

and

adding the option of adding NVGs to units as they spawn in the cases where the unit's default gears do not have NVGs by default.

**Comment by Cyruz143** [comment]
```gunLights``` are on auto by default in A3 if they have them, you can add them via Admiral Events if required and https://github.com/kami-/admiral/pull/37 closes NVGs.
