### ISSUE TITLE
Locking vehicles

### ISSUE THREAD

**Issue by Cyruz143** [kami-/admiral#27]
Ability to set vehicles spawned by Admiral to locked to avoid unbalancing missions / adding a bit more realism, pretty sure USMC don't know how to drive T72's etc.

**Comment by Winter259** [comment]
https://community.bistudio.com/wiki/lock

**Comment by Cyruz143** [comment]
I know that, just not sure if it respects the move in commands or not. e.g. If you lock a vehicle and then fill it with crew, will it cause issues.

**Comment by Cyruz143** [comment]
Closing, can use admiral events to lock vehicles if required but shouldn't be default.
