### ISSUE TITLE
No CQC in (some) BI military buildings

### ISSUE THREAD

**Issue by dancemoox** [kami-/admiral#32]
CQC units won't spawn in some small Altis and Stratis military buildings despite them having building positions. Examples below (green colour version), same applies to other colour variations. Given many outposts are made up exclusively of these small buildings some cqc units would be appreciated.

Land_Cargo_House_V1_F
Land_Cargo_Patrol_V1_F

Admiral will spawn in the larger Land_Cargo_Tower_V1_F and Land_Cargo_HQ_V1_F.

Big list o'classnames with pictures: https://community.bistudio.com/wiki/Arma_3_CfgVehicles_EMPTY

**Comment by Cyruz143** [comment]
Need to do some testing with the following command to see if we can figure out whats going on.

``` sqf
[_building buildingPos _i] call adm_cqc_fnc_isPositionInBuilding
```

**Comment by Cyruz143** [comment]
https://github.com/kami-/admiral/blob/63172649050a6477997a321ef3d9f87b5a76de6f/admiral/cqc_functions.sqf#L51-L60

Kami, fancy a test branch with the following code to see what impact this has? Should allow units to spawn other than inside buildings with roof tops.

```c++
adm_cqc_fnc_isPositionInBuilding = {
    FUN_ARGS_1(_pos);

    private["_pos", "_posAbove", "_isValidPos"];
    _posAbove = [_pos select 0, _pos select 1, (_pos select 2) + 30];
    _isValidPos = !(lineIntersects [ATLtoASL _pos, ATLtoASL _pos]);

    _isValidPos;
};
````

**Comment by Cyruz143** [comment]
Ok so the good:
http://i.imgur.com/Hz6rdVA.jpg

and the not so good:
http://i.imgur.com/y9RzWWn.jpg

There legit ```buildingPos``` positions but I don't know if it looks a bit stupid. Also no dice on your Land_Cargo_House_V1_F& Land_Cargo_Patrol_V1_F. They've not got ```buildingPos``` defined.

**Comment by Winter259** [comment]
A concern I have is whether the AI is intelligent enough to not wander off the side of the building once it gets engaged...

**Comment by Cyruz143** [comment]
Don't seem to move when they get engaged, might be another story in actual testing within a proper mission though. @kami- what do you think?

**Comment by Satire-** [comment]
Would it be possible to have the roof check on a condition, similar to how min height currently is? Or possibly have a selectable three state system via array? (Current roof check, new buildingpos check only or an inverted roof check to place units only on roofless spots for lookouts) Would give a lot of mission making flexibility.

**Comment by Winter259** [comment]
I'll write up a prototype if I find the time tomorrow.

**Comment by Cyruz143** [comment]
@Winter259 only two months so far...

**Comment by Winter259** [comment]
Still less than six.

**Comment by Cyruz143** [comment]
Resolved with https://github.com/kami-/admiral/pull/59
