### ISSUE TITLE
 adm_api_fnc_disableCamp throws error in expression

### ISSUE THREAD

**Issue by insane00** [kami-/admiral#80]
Deactivating an active ondemand zone with the [zonename] call adm_api_fnc_disableCamp; throws a nice chunk of errors into RPT logfile now, zone continues to spawn AI after trigger executed

21:41:45 Error in expression <   _zone = (_this) select 0;;

((_zone) select 11 set [1,false]);
;
};

adm_camp>
21:41:45   Error position: <select 11 set [1,false]);
;
};

adm_camp>
21:41:45   Error select: Type Object, expected Array,String,Config entry
21:41:45 File x\ark\addons\admiral\camp_functions.sqf, line 145
21:41:45 Error in expression <   _zone = (_this) select 0;;

((_zone) select 11 set [1,false]);
;
};

adm_camp>
21:41:45   Error position: <select 11 set [1,false]);
;
};

adm_camp>
21:41:45   Error Generic error in expression
21:41:45 File x\ark\addons\admiral\camp_functions.sqf, line 145

**Comment by kami-** [comment]
Use the second name field, which is grouped with the other zone fields, not the first one.
